import philly from '../images/uvodna2.jpg'
import tiktokPasta from '../images/tiktok pasta.jpg'
import ovsenaKasa from '../images/ovsena kasa.jpg'
import griz from '../images/griz.jpg'
import tostJaja from '../images/tost jaja.jpg'
import krilca from '../images/krilca.jpg'
import panko from '../images/panko.jpg'
import burito from '../images/burito.jpg'
import burger from '../images/vecera.jpg'
import pica from '../images/pica.jpg'
import losos from '../images/losos.jpg'
import sendvic from '../images/sendvic.jpg'
import chia from '../images/cia.jpg'
import pesto from '../images/pesto pasta.jpg'
import pastaPecurke from '../images/pasta pecurka.jpg'
import cheesecake from '../images/cheesecake.jpg'
import mus from '../images/mus.jpg'
import rolnice from '../images/rolnice.jpg'
import split from '../images/split.png'
import cufte from '../images/cufte.jpg'
import steak from '../images/steak.jpg'
import makaroneSir from '../images/makarone sir.jpg'
import tostAvokado from '../images/jaja avokado.jpg'
import palacinke from '../images/palacinke recept.jpg'

const pilule = [
    {
        id: 1,
        slika: philly,
        naslov:"-PHILLY CHEESESTEAK-",
        opis: "Sočno belo meso pažljivo začinjeno i proprženo sa paprikom, crnim i belim lukom, spaja se sa topljenim kačkavaljem u hrskavom somunu. Svaki zalogaj odiše bogatstvom ukusa zahvaljujući kombinaciji začina kao što su bosiljak, origano, chilli flakes i biber, dok puter daje završnu glatkoću i aromu. Inspirisano legendarnim Philly cheesesteakom, ali prilagođeno lokalnim ukusima, ovo jelo je idealan spoj klasičnog američkog sendviča i domaće kuhinje. Savršeno za ručak koji će te zasititi i oduševiti u svakom zalogaju.",
        vrsta: "ručak",
        vreme: "40min",
        sastojci: [
            { naziv: "belo meso", kolicina: 150, jedinica: "gr" },
            { naziv: "kačkavalj", kolicina: 50, jedinica: "gr" },
            { naziv: "paprika", kolicina: 1, jedinica: "kom" },
            { naziv: "crni luk", kolicina: 1, jedinica: "kom" },
            { naziv: "beli luk", kolicina: 3, jedinica: "čena" },
            { naziv: "somun", kolicina: 1, jedinica: "kom" },
            { naziv: "so", kolicina: 3, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" },
            { naziv: "chilli flakes", kolicina: 5, jedinica: "gr" },
            { naziv: "bosiljak", kolicina: 5, jedinica: "gr" },
            { naziv: "origano", kolicina: 5, jedinica: "gr" },
            { naziv: "puter", kolicina: 5, jedinica: "gr" }
        ],
        priprema: "opis pripreme",
        kalorije: 942,
        porcije: 1,
    },
    {
        id: 2,
        slika: tiktokPasta,
        naslov: "-PASTA SA FETOM I ČERI PARADAJZOM-",
        opis: "Savršeno kremasta i bogata pasta napravljena od pečenog čeri paradajza i rastopljenog feta sira, spaja jednostavne sastojke u eksploziju mediteranskih ukusa. Svaki zalogaj sadrži slatkoću paradajza, slanost fete i aromatične note belog luka u prahu, origana i bosiljka. Maslinovo ulje povezuje sve u jedinstvenu teksturu, dok se kuvanje u rerni pretvara u pravo kulinarsko uživanje. Ovaj obrok je lagan, ali zasitan, idealan za ručak koji donosi toplotu i svežinu u isto vreme – bez puno truda, a sa maksimalnim ukusom.",
        vrsta: "ručak",
        vreme: "60min",
        sastojci: [
            { naziv: "pasta", kolicina: 170, jedinica: "gr" },
            { naziv: "čeri paradajz", kolicina: 500, jedinica: "gr" },
            { naziv: "feta sir", kolicina: 250, jedinica: "gr" },
            { naziv: "so", kolicina: 3, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" },
            { naziv: "bosiljak", kolicina: 5, jedinica: "gr" },
            { naziv: "origano", kolicina: 5, jedinica: "gr" },
            { naziv: "beli luk u prahu", kolicina: 5, jedinica: "gr" },
            { naziv: "maslinovo ulje", kolicina: 15, jedinica: "gr" }
        ],
        priprema: "opis pripreme",
        kalorije: 1492,
        porcije: 2,
    },
    {
        id: 3,
        slika: ovsenaKasa,
        naslov: "-OVSENA KAŠA SA VOĆEM-",
        opis: "Ovsena kaša sa voćem je idealan doručak za one koji žele brz, zdrav i ukusan početak dana. Kombinacija kremastog jogurta i ovsenih pahuljica daje savršenu bazu, dok med, cimet i kakao unose slatke i tople note u svaku kašiku. Chia i lanene semenke dodaju hranljivu vrednost i teksturu, a voće – banana i borovnice – unose osvežavajuću slatkoću i boje. Sve zajedno stvara savršen balans između laganog i zasitnog obroka koji se priprema za svega nekoliko minuta, a energiju daje za ceo dan.",
        vrsta: "doručak",
        vreme: "5min",
        sastojci: [
            { naziv: "ovsene pahuljice", kolicina: 30, jedinica: "gr" },
            { naziv: "jogurt", kolicina: 200, jedinica: "gr" },
            { naziv: "med", kolicina: 15, jedinica: "gr" },
            { naziv: "cimet", kolicina: 1, jedinica: "gr" },
            { naziv: "mleveni lan", kolicina: 3, jedinica: "gr" },
            { naziv: "kakao", kolicina: 5, jedinica: "gr" },
            { naziv: "chia semenke", kolicina: 5, jedinica: "gr" },
            { naziv: "banana", kolicina: 1, jedinica: "kom" },
            { naziv: "borovnice", kolicina: 20, jedinica: "gr" }
        ],
        priprema: "opis pripreme",
        kalorije: 445,
        porcije: 1,
    },
    {
        id: 4,
        slika: griz,
        naslov:"-GRIZ SA KAKAOM I VOĆEM-",
        opis: "Griz sa kakaom i voćem je brz, ukusan i kremast doručak koji pruža savršenu ravnotežu energije. Toplo mleko i griz stvaraju bogatu, svilenu teksturu, dok kakao unosi bogat čokoladni ukus, a med dodaje slatkoću. Banana daje prirodnu sočnost i svežinu, čineći ovo jelo ne samo ukusnim već i hranljivim. Ovaj doručak je savršeno jednostavan, ali zasitan, idealan za početak dana ili kao brza užina, koja vas puni do sledećeg obroka.",
        vrsta: "doručak",
        vreme: "10min",
        sastojci: [
            { naziv: "griz", kolicina: 40, jedinica: "gr" },
            { naziv: "mleko", kolicina: 300, jedinica: "ml" },
            { naziv: "banana", kolicina: 1, jedinica: "kom" },
            { naziv: "med", kolicina: 15, jedinica: "gr" },
            { naziv: "kakao", kolicina: 5, jedinica: "gr" },
        ],
        priprema: "opis pripreme",
        kalorije: 493,
        porcije: 1,
        objectPosition: "30% 10%"
    },
    {
        id: 5,
        slika: tostJaja,
        naslov: "-TOST SA JAJIMA I PARADAJZOM-",
        opis: "Tost sa jajima i paradajzom je jednostavan, ali ukusan obrok koji je savršen za večeru. Hleb se tosti na puteru, dok se jaja prže do savršenog stepena, sa bogatim kajmakom koji dodaje kremastu teksturu. Paradajz unosi svežinu, a začini poput origana, bibera i čili pahuljica daju jelu dodatnu dimenziju ukusa. Ovaj obrok je brz i hranljiv, idealan za one koji žele ukusan obrok bez puno pripreme, a opet sa svim potrebnim nutrijentima.",
        vrsta: "večera",
        vreme: "10min",
        sastojci: [
            { naziv: "hleb", kolicina: 2, jedinica: "kom" },
            { naziv: "jaje", kolicina: 2, jedinica: "kom" },
            { naziv: "kajmak", kolicina: 10, jedinica: "gr" },
            { naziv: "paradajz", kolicina: 1, jedinica: "kom" },
            { naziv: "so", kolicina: 2, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" },
            { naziv: "chilli flakes", kolicina: 3, jedinica: "gr" },
            { naziv: "puter", kolicina: 10, jedinica: "gr" },
            { naziv: "origano", kolicina: 1, jedinica: "gr" }
        ],
        priprema: "opis pripreme",
        kalorije: 438,
        porcije: 1,
    },
    {
        id: 6,
        slika: krilca,
        naslov: "-HRSKAVA PILEĆA KRILCA-",
        opis: "Hrsava pileća krilca su savršen izbor za ljubitelje mesa koji žele uživati u hrskavom i ukusnom obroku. Krilca se pripremaju uz prah za pecivo, koji im daje dodatnu hrskavost, dok so i biber obogaćuju njihov prirodan ukus. Jednostavno za pripremu i savršeno za ručak, ovo jelo pruža pravu mešavinu ukusa i tekstura, idealno za ljubitelje pilećeg mesa.",
        vrsta: "ručak",
        vreme: "60min",
        sastojci: [
            { naziv: "krilca", kolicina: 8, jedinica: "kom" },
            { naziv: "prašak za pecivo", kolicina: 4, jedinica: "gr" },
            { naziv: "so", kolicina: 4, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" }
        ],
        priprema: "opis pripreme",
        kalorije: 706,
        porcije: 1,
    },
    {
        id: 7,
        slika: panko,
        naslov:"-POHOVANO BELO MESO-",
        opis: "Pohovano belo meso je klasik koji nikada ne izlazi iz mode. Piletina je uvaljana u brašno, jaje i panko prezle, a potom pržena do savršene hrskavosti. So, biber, origano i chilli flakes dodaju savršenu začinsku notu, dok puter doprinosi bogatstvu okusa. Ovo jelo je ukusan i zasitan ručak, koji će zadovoljiti i najizbirljivije gurmane.",
        vrsta: "ručak",
        vreme: "40min",
        sastojci: [
            { naziv: "piletina", kolicina: 200, jedinica: "gr" },
            { naziv: "panko prezle", kolicina: 50, jedinica: "gr" },
            { naziv: "brašno", kolicina: 30, jedinica: "gr" },
            { naziv: "jaje", kolicina: 1, jedinica: "kom" },
            { naziv: "so", kolicina: 2, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" },
            { naziv: "chilli flakes", kolicina: 3, jedinica: "gr" },
            { naziv: "puter", kolicina: 10, jedinica: "gr" },
            { naziv: "origano", kolicina: 1, jedinica: "gr" }
        ],
        priprema: "opis pripreme",
        kalorije: 659,
        porcije: 1,
    },
    {
        id: 8,
        slika: burito,
        naslov: "-BURITO SA BELIM MESOM-",
        opis: "Ovaj ukusan burito sa belim mesom je savršen obrok za večeru, sa laganim i osvežavajućim sastojcima poput piletine, humusa, paradajza, krastavca i začina. Tortilja u koju se sve upakuje dodaje savršen balans, a začini poput origana i chilli flakes-a daju mu dodatnu dozu ukusa. Brzo se sprema i može da bude savršen obrok za one koji žele nešto ukusno, ali i hranljivo. Svi sastojci zajedno čine ovaj burito izuzetno bogatim ukusima, dok istovremeno pruža dobar izvor proteina i zdravih masti.",
        vrsta: "večera",
        vreme: "30min",
        sastojci: [
            { naziv: "piletina", kolicina: 150, jedinica: "gr" },
            { naziv: "humus", kolicina: 20, jedinica: "gr" },
            { naziv: "tortilja", kolicina: 150, jedinica: "ml" },
            { naziv: "paradajz", kolicina: 0.5, jedinica: "kom" },
            { naziv: "krastavac", kolicina: 0.25, jedinica: "kom" },
            { naziv: "so", kolicina: 2, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" },
            { naziv: "chilli flakes", kolicina: 3, jedinica: "gr" },
            { naziv: "beli luk", kolicina: 3, jedinica: "kom" },
            { naziv: "puter", kolicina: 10, jedinica: "gr" },
            { naziv: "origano", kolicina: 2, jedinica: "gr" }
        ],
        priprema: "opis pripreme",
        kalorije: 516,
        porcije: 1,
    },
    {
        id: 9,
        slika: burger,
        naslov: "-BURGER-",
        opis: "Ovaj sočan i ukusan burger savršen je za brzu večeru, sa sočnim junećim mesom, svežim povrćem i začinima koji podižu sve ukuse. Piletina je jednostavno začinjena sa soli, biberom i origano, dok crni luk, beli luk i paradajz dodaju svežinu. Kiseli krastavčići i tucana paprika daju mu dodatnu aromu i začinjenost. Somun, u kojem se sve servira, doprinosi bogatom teksturalnom kontrastu, čineći ovaj burger savršenim obrokom za ljubitelje brze hrane.",
        vrsta: "večera",
        vreme: "15min",
        sastojci: [
            { naziv: "juneće mleveno meso", kolicina: 200, jedinica: "gr" },
            { naziv: "somun", kolicina: 1, jedinica: "kom" },
            { naziv: "crni luk", kolicina: 1, jedinica: "kom" },
            { naziv: "beli luk", kolicina: 2, jedinica: "čena" },
            { naziv: "paradajz", kolicina: 0.5, jedinica: "kom" },
            { naziv: "kiseli krastavčići", kolicina: 2, jedinica: "kom" },
            { naziv: "so", kolicina: 2, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" },
            { naziv: "origano", kolicina: 2, jedinica: "gr" },
            { naziv: "tucana paprika", kolicina: 1, jedinica: "kašičica" }
        ],
        priprema: "opis pripreme",
        kalorije: 870,
        porcije: 1,
    },
    {
        id: 10,
        slika: pica,
        naslov:"-PICA-",
        opis: "Pica je omiljeni obrok mnogih, a u ovom receptu kombinuju se sočni kulen, pečurke, kiseli krastavčići i bogat kačkavalj, sve na hrskavom domaćem testu. Uz dodatak origana, bosiljka i začina, ova pizza donosi savršen balans ukusa. Savršena je za sve ljubitelje italijanske hrane, a može biti idealan obrok za večeru sa prijateljima ili porodicom. Sa bogatstvom sastojaka, lako možete da je podelite u više porcija i uživate u svakom zalogaju.",
        vrsta: "ručak",
        vreme: "50min",
        sastojci: [
            { naziv: "brašno", kolicina: 350, jedinica: "gr" },
            { naziv: "so", kolicina: 6, jedinica: "gr" },
            { naziv: "voda", kolicina: 220, jedinica: "ml" },
            { naziv: "maslinovo ulje", kolicina: 10, jedinica: "ml" },
            { naziv: "kvasac", kolicina: 10, jedinica: "gr" },
            { naziv: "kulen", kolicina: 100, jedinica: "gr" },
            { naziv: "kečap", kolicina: 50, jedinica: "ml" },
            { naziv: "kačkavalj", kolicina: 350, jedinica: "gr" },
            { naziv: "pečurke", kolicina: 5, jedinica: "kom" },
            { naziv: "kiseli krastavčići", kolicina: 6, jedinica: "kom" },
            { naziv: "origano", kolicina: 5, jedinica: "gr" },
            { naziv: "bosiljak", kolicina: 3, jedinica: "gr" },
            { naziv: "beli luk", kolicina: 5, jedinica: "čena" },
            { naziv: "chilli flakes", kolicina: 5, jedinica: "gr" }
        ],
        priprema: "opis pripreme",
        kalorije: 3240,
        porcije: 4,
    },
    {
        id: 11,
        slika: losos,
        naslov: "-LOSOS I POMFRIT-",
        opis: "Ovaj obrok spaja sočan losos sa hrskavim domaćim pomfritom, uz dodatak limuna za osvežavajući šmek. Prženi krompir u suncokretovom i maslinovom ulju daje savršenu teksturu i ukus, dok soja sos i kečap čine dodatnu dimenziju okusa. Idealno je jelo za uživanje u zdravoj i ukusnoj večeri, a kombinacija lososa i pomfrita čini obrok koji je i ukusan i zasitan.",
        vrsta: "ručak",
        vreme: "30min",
        sastojci: [
            { naziv: "losos", kolicina: 300, jedinica: "gr" },
            { naziv: "krompir", kolicina: 200, jedinica: "gr" },
            { naziv: "kečap", kolicina: 50, jedinica: "ml" },
            { naziv: "suncokretovo ulje", kolicina: 200, jedinica: "ml" },
            { naziv: "maslinovo ulje", kolicina: 10, jedinica: "ml" },
            { naziv: "limun", kolicina: 0.25, jedinica: "kom" },
            { naziv: "soja", kolicina: 20, jedinica: "ml" },
            { naziv: "so", kolicina: 2, jedinica: "gr" },
            { naziv: "biber", kolicina: 2, jedinica: "gr" },
            { naziv: "tucana paprika", kolicina: 2, jedinica: "2gr" }
        ],
        priprema: "opis pripreme",
        kalorije: 1040,
        porcije: 1,
    },
    {
        id: 12,
        slika: sendvic,
        naslov: "-TOPLI SENDVIČI-",
        opis: "Topli sendviči su savršen izbor za brz, ali ukusan doručak. Hrskavi hleb, rastopljeni kačkavalj, aromatični kečap i začini poput origana čine ovaj sendvič neodoljivim, dok kulen dodaje dodatni sloj bogatog ukusa. Uz malo putera, ovaj jednostavan, a ukusan obrok može biti odličan način da započneš dan sa energijom.",
        vrsta: "doručak",
        vreme: "10min",
        sastojci: [
            { naziv: "hleb", kolicina: 2, jedinica: "kom" },
            { naziv: "kačkavalj", kolicina: 30, jedinica: "gr" },
            { naziv: "kečap", kolicina: 10, jedinica: "ml" },
            { naziv: "origano", kolicina: 1, jedinica: "gr" },
            { naziv: "kulen", kolicina: 15, jedinica: "gr" },
            { naziv: "puter", kolicina: 5, jedinica: "gr" },
        ],
        priprema: "opis pripreme",
        kalorije: 406,
        porcije: 1,
    },
    {
        id: 13,
        slika: chia,
        naslov:"-CHIA PUDING-",
        opis: "Chia puding je ukusan i zdrav dezert koji je brz za pripremu. Chia semenke upijaju mleko i stvaraju želatinastu teksturu, dok med dodaje prirodnu slatkoću. Služeni sa svežim jagodama i komadićima crne čokolade, ovaj puding postaje pravo uživanje u ukusu i hranljivim sastojcima. Idealno je rešenje za desert koji je i ukusan i hranljiv.",
        vrsta: "dezert",
        vreme: "5min",
        sastojci: [
            { naziv: "chia semenke", kolicina: 30, jedinica: "gr" },
            { naziv: "mleko", kolicina: 150, jedinica: "ml" },
            { naziv: "med", kolicina: 15, jedinica: "gr" },
            { naziv: "jagode", kolicina: 7, jedinica: "kom" },
            { naziv: " crna čokolada", kolicina: 20, jedinica: "gr" }
        ],
        priprema: "opis pripreme",
        kalorije: 425,
        porcije: 1,
    },
    {
        id: 14,
        slika: pesto,
        naslov: "-PESTO PASTA-",
        opis: "Pesto pasta je jednostavno jelo koje spaja ukuse svežeg bosiljka, začinskog origana i bogatog pesto sosa. Čeri paradajz dodaje svežinu, dok pavlaka za kuvanje daje kremastu teksturu koja čini svaki zalogaj posebnim. Savršeno je za brzi ručak koji je ukusan, zasitan i bogat vitaminima. Idealno je za ljubitelje italijanske kuhinje koji žele da uživaju u jednostavnom, ali punom okusu.",
        vrsta: "ručak",
        vreme: "20min",
        sastojci: [
            { naziv: "pasta", kolicina: 170, jedinica: "gr" },
            { naziv: "pesto", kolicina: 95, jedinica: "gr" },
            { naziv: "čeri paradajz", kolicina: 300, jedinica: "gr" },
            { naziv: "pavlaka za kuvanje", kolicina: 125, jedinica: "ml" },
            { naziv: "so", kolicina: 3, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" },
            { naziv: "bosiljak", kolicina: 5, jedinica: "gr" },
            { naziv: "origano", kolicina: 5, jedinica: "gr" }
        ],
        priprema: "opis pripreme",
        kalorije: 986,
        porcije: 2,
    },
    {
        id: 15,
        slika:pastaPecurke,
        naslov: "-PASTA SE BELIM MESOM I PEČURKAMA-",
        opis: "Pasta sa belim mesom i pečurkama je ukusno i kremasto jelo koje kombinuje nežno belo meso i bogate pečurke, u savršenom spoju sa kremastom pavlakom za kuvanje. Začini poput origana, bosiljka, i tucane paprike dodaju dubinu okusa, dok pasta upija sve te ukuse. Jelo je brzo, zasitno i idealno za svaki obrok kada želite nešto brzo i ukusanog.",
        vrsta: "ručak",
        vreme: "40min",
        sastojci: [
            { naziv: "belo meso", kolicina: 150, jedinica: "gr" },
            { naziv: "pečurke", kolicina: 200, jedinica: "gr" },
            { naziv: "pasta", kolicina: 170, jedinica: "gr" },
            { naziv: "pavlaka za kuvanje", kolicina: 200, jedinica: "ml" },
            { naziv: "so", kolicina: 5, jedinica: "gr" },
            { naziv: "biber", kolicina: 2, jedinica: "gr" },
            { naziv: "tucana paprika", kolicina: 5, jedinica: "gr" },
            { naziv: "chilli flakes", kolicina: 5, jedinica: "gr" },
            { naziv: "bosiljak", kolicina: 5, jedinica: "gr" },
            { naziv: "origano", kolicina: 5, jedinica: "gr" }
        ],
        priprema: "Skuvaj pastu u posoljenoj vodi, procedi i sačuvaj malo vode od kuvanja.\n Iseci belo meso i proprži ga na ulju dok ne porumeni. Dodaj seckane pečurke i prži dok ne omekšaju. Ubaci začine (so, biber, tucana paprika, chilli flakes, bosiljak, origano) i kratko proprži. Sipaj pavlaku za kuvanje i krčkaj nekoliko minuta dok se sos ne zgusne. Ubaci pastu, sve promešaj i po potrebi dodaj malo vode od kuvanja da razrediš sos. Služi toplo, po želji uz parmezan ili sveži bosiljak.",
        kalorije: 1153,
        porcije: 2,
    },
    {
        id: 16,
        slika: cheesecake,
        naslov:"-CHEESECAKE-",
        opis: "Cheesecake sa malinama je kremasti dezert koji spaja bogatstvo kisele pavlake i slatkoću malina. U osnovi je hrskava kora od mlevene plazme i putera, dok je gornji sloj bogat kremom od Ella sira, slatke pavlake i šećera, sa dodatkom želatina koji daje stabilnost. Na vrhu se nalazi osvežavajući sloj malina, sa malo šećera i vanilin šećera za dodatnu aromu. Savršen spoj bogatog, ali nežnog ukusa i osvežavajuće voćne note malina.",
        vrsta: "dezert",
        vreme: "80min",
        sastojci: [
            { naziv: "mlevena plazma", kolicina: 300, jedinica: "gr" },
            { naziv: "puter", kolicina: 125, jedinica: "gr" },
            { naziv: "mleko", kolicina: 70, jedinica: "ml" },
            { naziv: "Ella sir", kolicina: 450, jedinica: "gr" },
            { naziv: "slatka pavlaka", kolicina: 500, jedinica: "ml" },
            { naziv: "želatin", kolicina: 3, jedinica: "kesice" },
            { naziv: "šećer u prahu", kolicina: 200, jedinica: "gr" },
            { naziv: "vanilin šećer", kolicina: 1, jedinica: "kesica" },
            { naziv: "kremfix", kolicina: 1, jedinica: "kesica" },
            { naziv: "malina", kolicina: 450, jedinica: "gr" },
            { naziv: "šećer", kolicina: 50, jedinica: "gr" }
        ],
        priprema: "opis pripreme",
        kalorije: 7170,
        porcije: 8,
    },
    {
        id: 17,
        slika: mus,
        naslov: "-ČOKOLADNI MUS-",
        opis: "Čokoladni mus je kremasti, bogati dezert savršen za ljubitelje čokolade. Kremasta tekstura se postiže kombinovanjem otopljene crne čokolade sa umućenim jajima i slatkom pavlakom. Puter i šećer u prahu dodaju glatkoću i dodatnu slatkoću. Ovaj mus je idealan za uživanje u malim porcijama, a njegov intenzivan čokoladni ukus je prava poslastica za sve sladokusce.",
        vrsta: "dezert",
        vreme: "15min",
        sastojci: [
            { naziv: "crna čokolada", kolicina: 125, jedinica: "gr" },
            { naziv: "jaja", kolicina: 3, jedinica: "kom" },
            { naziv: "slatka pavlaka", kolicina: 120, jedinica: "ml" },
            { naziv: "puter", kolicina: 10, jedinica: "gr" },
            { naziv: "šećer u prahu", kolicina: 25, jedinica: "gr" }
        ],
        priprema: "opis pripreme",
        kalorije: 1420,
        porcije: 2,
    },
    {
        id: 18,
        slika: rolnice,
        naslov: "-CIMET ROLNICE-",
        opis: "Cimet rolnice su ukusan i mirisan dezert koji je savršen za ljubitelje slatkiša i začina. Kvasac, brašno i šećer se kombinuju sa kremastim puterom, cimetom i vanilin ekstraktom da bi se stvorila bogata tekstura i sladak, začinski ukus. Ovaj recept je odličan za svakog ko želi da uživa u svežim i mekanim rolnicama sa bogatim punjenjem, idealnim za doručak ili užinu.",
        vrsta: "dezert",
        vreme: "60min",
        sastojci: [
            { naziv: "kvasac", kolicina: 1, jedinica: "kesica" },
            { naziv: "mleko", kolicina: 350, jedinica: "ml" },
            { naziv: "šećer", kolicina: 100, jedinica: "gr" },
            { naziv: "puter", kolicina: 265, jedinica: "gr" },
            { naziv: "so", kolicina: 3, jedinica: "gr" },
            { naziv: "jaje", kolicina: 2, jedinica: "kom" },
            { naziv: "brašno", kolicina: 500, jedinica: "gr" },
            { naziv: "smeđi šećer", kolicina: 200, jedinica: "gr" },
            { naziv: "cimet", kolicina: 20, jedinica: "gr" },
            { naziv: "šećer u prahu", kolicina: 150, jedinica: "gr" },
            { naziv: "kremsir", kolicina: 60, jedinica: "gr" },
            { naziv: "vanilin ekstrakt", kolicina: 3, jedinica: "ml" }
        ],
        priprema: "opis pripreme",
        kalorije: 5953,
        porcije: 12,
    },
    {
        id: 19,
        slika: split,
        naslov:"-BANANA SPLIT-",
        opis: "Banana Split je ukusan i osvežavajući dezert koji kombinuje sladoled, voće i šlag u savršenoj harmoniji ukusa. U ovoj verziji, osnovu čini sočna banana, na kojoj se nalazi kugla sladoleda od banane, čokolade i vanile, dok je sve preliveno čokoladnim prelivom, šlagom i dekorisano sa nekoliko višanja. Ovaj dezert je brz i jednostavan za pripremu, a istovremeno pruža bogatstvo ukusa koji se savršeno kombinuju u svakom zalogaju. Idealno je kao osvežavajući završetak obroka ili za uživanje u toplim letnjim danima.",
        vrsta: "dezert",
        vreme: "5min",
        sastojci: [
            { naziv: "banana", kolicina: 1, jedinica: "kugla" },
            { naziv: "sladoled banana", kolicina: 1, jedinica: "kugla" },
            { naziv: "sladoled cokolada", kolicina: 1, jedinica: "kugla" },
            { naziv: "sladoled vanila", kolicina: 1, jedinica: "kom" },
            { naziv: "preliv cokolada", kolicina: 10, jedinica: "gr" },
            { naziv: "šlag", kolicina: 1, jedinica: "kugla" },
            { naziv: "višnja", kolicina: 3, jedinica: "kom" }
        ],
        priprema: "opis pripreme",
        kalorije: 592,
        porcije: 1,
    },
    {
        id: 20,
        slika: cufte,
        naslov: "-JUNEĆE ĆUFTE SA PIREOM-",
        opis: "Juneće ćufte sa pireom je klasičan i ukusan obrok koji spaja bogatstvo mesa i kremastu teksturu pire krompira. Juneće meso se meša sa začinima i prezlama, oblikuje u ćufte, a zatim se peče dok ne postane sočno i savršeno začinjeno. Pire krompir je napravljen sa malo mleka i prstohvatom muskatnog oraha, što mu daje dodatnu mekoću i bogatstvo ukusa. Na kraju, sve se preliva paradajz sosom, što dodaje sočnost i blagost ovom jelu. Ovo je savršen obrok za ljubitelje tradicionalne kuhinje.",
        vrsta: "ručak",
        vreme: "50min",
        sastojci: [
            { naziv: "juneće mleveno meso", kolicina: 400, jedinica: "gr" },
            { naziv: "prezle", kolicina: 30, jedinica: "gr" },
            { naziv: "krompir", kolicina: 400, jedinica: "gr" },
            { naziv: "mleko", kolicina: 20, jedinica: "ml" },
            { naziv: "muskatni orah", kolicina: 1, jedinica: "prstohvat" },
            { naziv: "paradajz sos", kolicina: 200, jedinica: "ml" },
            { naziv: "so", kolicina: 5, jedinica: "gr" },
            { naziv: "biber", kolicina: 2, jedinica: "gr" },
            { naziv: "tucana paprika", kolicina: 2, jedinica: "gr" },
            { naziv: "origano", kolicina: 5, jedinica: "gr" }
        ],
        priprema: "opis pripreme",
        kalorije: 1072,
        porcije: 2,
    },
    {
        id: 21,
        slika: steak,
        naslov: "-STEAK-",
        opis: "Steak je sočan komad mesa, obično biftek, koji je brzo pečen u tiganju sa minimalnim začinima poput soli, bibera i maslinovog ulja. Dodavanje belog luka i ruzmarina doprinosi intenzivnijem ukusu, dok puter na kraju dodaje bogatstvo i sočnost jelu. Ovo jelo je jednostavno, ali ukusno, savršeno za ljubitelje mesa.",
        vrsta: "ručak",
        vreme: "15min",
        sastojci: [
            { naziv: "biftek", kolicina: 300, jedinica: "gr" },
            { naziv: "beli luk", kolicina: 5, jedinica: "čena" },
            { naziv: "ruzmarin", kolicina: 1, jedinica: "kom" },
            { naziv: "puter", kolicina: 25, jedinica: "gr" },
            { naziv: "maslinovo ulje", kolicina: 15, jedinica: "ml" },
            { naziv: "so", kolicina: 5, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" }
        ],
        priprema: "opis pripreme",
        kalorije: 870,
        porcije: 1,
    },
    {
        id: 22,
        slika: makaroneSir,
        naslov:"-MAKARONE SA SIROM-",
        opis: "Ovaj recept za makarone sa sirom je brz i ukusan obrok, idealan za večeru. Pasta se kombinuje sa kremastim feta sirom i pavlakom, uz svež paradajz, beli luk i začine kao što su bosiljak i origano, što daje odličnu ravnotežu ukusa. Jednostavno, a vrlo zasitno!",
        vrsta: "večera",
        vreme: "20min",
        sastojci: [
            { naziv: "pasta", kolicina: 170, jedinica: "gr" },
            { naziv: "feta", kolicina: 250, jedinica: "gr" },
            { naziv: "pavlaka", kolicina: 30, jedinica: "gr" },
            { naziv: "paradajz", kolicina: 2, jedinica: "kom" },
            { naziv: "maslinovo ulje", kolicina: 10, jedinica: "ml" },
            { naziv: "beli luk", kolicina: 5, jedinica: "čena" },
            { naziv: "so", kolicina: 3, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" },
            { naziv: "beli luk u prahu", kolicina: 5, jedinica: "gr" },
            { naziv: "bosiljak", kolicina: 5, jedinica: "gr" },
            { naziv: "origano", kolicina: 5, jedinica: "gr" }
        ],
        priprema: "opis pripreme",
        kalorije: 1495,
        porcije: 2,
    },
    {
        id: 23,
        slika: tostAvokado,
        naslov: "-TOST SA JAJIMA I AVOKADOM-",
        opis: "Tost sa jajima i avokadom je jednostavan, ukusan i hranljiv doručak koji kombinuje kremasti avokado, bogata jaja i hrskav hleb, sa dodatkom začina koji obogaćuju ukus. Idealno je za početak dana, jer pruža dobar izvor zdravih masti, proteina i vlakana.",
        vrsta: "doručak",
        vreme: "15min",
        sastojci: [
            { naziv: "hleb", kolicina: 2, jedinica: "kom" },
            { naziv: "avokado", kolicina: 1, jedinica: "kom" },
            { naziv: "jaje", kolicina: 2, jedinica: "kom" },
            { naziv: "maslinovo ulje", kolicina: 10, jedinica: "ml" },
            { naziv: "so", kolicina: 2, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" },
            { naziv: "tucana paprika", kolicina: 3, jedinica: "gr" },
            { naziv: "origano", kolicina: 2, jedinica: "gr" }
        ],
        priprema: "opis pripreme",
        kalorije: 646,
        porcije: 1,
    },
    {
        id: 24,
        slika: palacinke,
        naslov: "-PALAČINKE-",
        opis: "Palačinke su omiljeni dezert koji je jednostavan za pripremu i može se prilagoditi različitim dodacima poput džema, čokolade, voća ili šlaga. Sastojci kao što su brašno, mleko, jaja i voda kombinuju se u glatku smesu koja se prži na tavi s malo ulja, dok vanilin ekstrakt dodaje prijatan miris i ukus. Palačinke su tanje i mekše, idealne za uživanje u kombinaciji sa raznim dodacima po želji. Ovaj brzi i ukusan desert može biti savršen za doručak ili užinu.",
        vrsta: "dezert",
        vreme: "25min",
        sastojci: [
            { naziv: "brašno", kolicina: 200, jedinica: "gr" },
            { naziv: "voda", kolicina: 200, jedinica: "ml" },
            { naziv: "mleko", kolicina: 200, jedinica: "ml" },
            { naziv: "jaje", kolicina: 2, jedinica: "kom" },
            { naziv: "suncokretovo ulje", kolicina: 15, jedinica: "ml" },
            { naziv: "vanilin ekstrakt", kolicina: 3, jedinica: "ml" }
        ],
        priprema: "opis pripreme",
        kalorije: 1082,
        porcije: 4,
    },

]

export default pilule;