import philly from '../images/uvodna2.jpg'
import tiktokPasta from '../images/tiktok pasta.jpg'
import ovsenaKasa from '../images/ovsena kasa.jpg'
import griz from '../images/griz.jpg'
import tostJaja from '../images/tost jaja.jpg'
import krilca from '../images/krilca.jpg'
import panko from '../images/panko.jpg'
import burito from '../images/burito.jpg'
import burger from '../images/vecera.jpg'
import pica from '../images/pica.jpg'
import losos from '../images/losos.jpg'
import sendvic from '../images/sendvic.jpg'
import chia from '../images/cia.jpg'
import pesto from '../images/pesto pasta.jpg'
import pastaPecurke from '../images/pasta pecurka.jpg'
import cheesecake from '../images/cheesecake.jpg'
import mus from '../images/mus.jpg'
import rolnice from '../images/rolnice.jpg'
import split from '../images/split.png'
import cufte from '../images/cufte.jpg'
import steak from '../images/steak.jpg'
import makaroneSir from '../images/makarone sir.jpg'
import tostAvokado from '../images/jaja avokado.jpg'
import palacinke from '../images/palacinke recept.jpg'

const pilule = [
    {
        id: 1,
        slika: philly,
        naslov:"-PHILLY CHEESESTEAK-",
        opis: "Sočno belo meso pažljivo začinjeno i proprženo sa paprikom, crnim i belim lukom, spaja se sa topljenim kačkavaljem u hrskavom somunu. Svaki zalogaj odiše bogatstvom ukusa zahvaljujući kombinaciji začina kao što su bosiljak, origano, chilli flakes i biber, dok puter daje završnu glatkoću i aromu. Inspirisano legendarnim Philly cheesesteakom, ali prilagođeno lokalnim ukusima, ovo jelo je idealan spoj klasičnog američkog sendviča i domaće kuhinje. Savršeno za ručak koji će te zasititi i oduševiti u svakom zalogaju.",
        vrsta: "ručak",
        vreme: 40,
        sastojci: [
            { naziv: "belo meso", kolicina: 150, jedinica: "gr" },
            { naziv: "kačkavalj", kolicina: 50, jedinica: "gr" },
            { naziv: "paprika", kolicina: 1, jedinica: "kom" },
            { naziv: "crni luk", kolicina: 1, jedinica: "kom" },
            { naziv: "beli luk", kolicina: 3, jedinica: "čena" },
            { naziv: "somun", kolicina: 1, jedinica: "kom" },
            { naziv: "so", kolicina: 3, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" },
            { naziv: "chilli flakes", kolicina: 5, jedinica: "gr" },
            { naziv: "bosiljak", kolicina: 5, jedinica: "gr" },
            { naziv: "origano", kolicina: 5, jedinica: "gr" },
            { naziv: "puter", kolicina: 5, jedinica: "gr" }
        ],
        priprema: "Iseci belo meso na trakice i proprži ga na malo putera dok ne dobije zlatnu boju.\nDodaj crni i beli luk, pa kad omekšaju, ubaci sečenu papriku.\nZačini sve solju, biberom, bosiljkom, origanom i chilli flakes-om.\nPrži još nekoliko minuta da se ukusi povežu.\nNa kraju ubaci rendani kačkavalj i mešaj dok se lepo ne otopi.\nSomun blago zagrej, pa ga raseci i napuni pripremljenim punjenjem.\nPo želji, možeš ga dodatno zapeći u tiganju ili rerni da spolja postane hrskav. Služi toplo, dok je sir još topao i rastegljiv.",
        savet: "Sir rastopiti na laganoj vatri uz puno mešanja, kako ne bi došlo do lepljenja sira za dno tiganja.",
        kalorije: 942,
        porcije: 1,
    },
    {
        id: 2,
        slika: tiktokPasta,
        naslov: "-PASTA SA FETOM I ČERI PARADAJZOM-",
        opis: "Savršeno kremasta i bogata pasta napravljena od pečenog čeri paradajza i rastopljenog feta sira, spaja jednostavne sastojke u eksploziju mediteranskih ukusa. Svaki zalogaj sadrži slatkoću paradajza, slanost fete i aromatične note belog luka u prahu, origana i bosiljka. Maslinovo ulje povezuje sve u jedinstvenu teksturu, dok se kuvanje u rerni pretvara u pravo kulinarsko uživanje. Ovaj obrok je lagan, ali zasitan, idealan za ručak koji donosi toplotu i svežinu u isto vreme – bez puno truda, a sa maksimalnim ukusom.",
        vrsta: "ručak",
        vreme: 60,
        sastojci: [
            { naziv: "pasta", kolicina: 170, jedinica: "gr" },
            { naziv: "čeri paradajz", kolicina: 500, jedinica: "gr" },
            { naziv: "feta sir", kolicina: 250, jedinica: "gr" },
            { naziv: "so", kolicina: 3, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" },
            { naziv: "bosiljak", kolicina: 5, jedinica: "gr" },
            { naziv: "origano", kolicina: 5, jedinica: "gr" },
            { naziv: "beli luk u prahu", kolicina: 5, jedinica: "gr" },
            { naziv: "maslinovo ulje", kolicina: 15, jedinica: "gr" }
        ],
        priprema: "U vatrostalnu posudu ubaciti čeri paradajz, feta sir, maslinovo ulje, origano, bosiljak, biber i so.\nSve dobro promešati i staviti u rernu na 200 stepeni oko 50 minuta.\nNakon toga, izvaditi iz rerne i sve dobro izgnječiti viljuškom.\nTreba natempirati da se pasta završi u isto vreme kada se smesa iz rerne skuva.\nKada je pasta gotova, sve sjediniti i dobro promešati.",
        savet: "Sačuvati malo vode od kuvanja paste, pa dodati u smesu iz rerne, kako bi se dobila kremastija tekstura.",
        kalorije: 1492,
        porcije: 2,
    },
    {
        id: 3,
        slika: ovsenaKasa,
        naslov: "-OVSENA KAŠA SA VOĆEM-",
        opis: "Ovsena kaša sa voćem je idealan doručak za one koji žele brz, zdrav i ukusan početak dana. Kombinacija kremastog jogurta i ovsenih pahuljica daje savršenu bazu, dok med, cimet i kakao unose slatke i tople note u svaku kašiku. Chia i lanene semenke dodaju hranljivu vrednost i teksturu, a voće – banana i borovnice – unose osvežavajuću slatkoću i boje. Sve zajedno stvara savršen balans između laganog i zasitnog obroka koji se priprema za svega nekoliko minuta, a energiju daje za ceo dan.",
        vrsta: "doručak",
        vreme: 5,
        sastojci: [
            { naziv: "ovsene pahuljice", kolicina: 30, jedinica: "gr" },
            { naziv: "jogurt", kolicina: 200, jedinica: "gr" },
            { naziv: "med", kolicina: 15, jedinica: "gr" },
            { naziv: "cimet", kolicina: 1, jedinica: "gr" },
            { naziv: "mleveni lan", kolicina: 3, jedinica: "gr" },
            { naziv: "kakao", kolicina: 5, jedinica: "gr" },
            { naziv: "chia semenke", kolicina: 5, jedinica: "gr" },
            { naziv: "banana", kolicina: 1, jedinica: "kom" },
            { naziv: "borovnice", kolicina: 20, jedinica: "gr" }
        ],
        priprema: "U činiju staviti ovsene pahuljice, jogurt, med, cimet, lanene semenke i kakao.\nSve dobro promešati i ostaviti da odstoji preko noći.\nUjutru dodati bananu i borovnice ili neko drugo voće po izboru i sve dobro promešati.",
        savet: "Ovsene pahuljice mogu da se ostave da odstoje i 10 minuta, ali je najbolje ostaviti ih preko noći.",
        kalorije: 445,
        porcije: 1,
    },
    {
        id: 4,
        slika: griz,
        naslov:"-GRIZ SA KAKAOM I VOĆEM-",
        opis: "Griz sa kakaom i voćem je brz, ukusan i kremast doručak koji pruža savršenu ravnotežu energije. Toplo mleko i griz stvaraju bogatu, svilenu teksturu, dok kakao unosi bogat čokoladni ukus, a med dodaje slatkoću. Banana daje prirodnu sočnost i svežinu, čineći ovo jelo ne samo ukusnim već i hranljivim. Ovaj doručak je savršeno jednostavan, ali zasitan, idealan za početak dana ili kao brza užina, koja vas puni do sledećeg obroka.",
        vrsta: "doručak",
        vreme: 10,
        sastojci: [
            { naziv: "griz", kolicina: 40, jedinica: "gr" },
            { naziv: "mleko", kolicina: 300, jedinica: "ml" },
            { naziv: "banana", kolicina: 1, jedinica: "kom" },
            { naziv: "med", kolicina: 15, jedinica: "gr" },
            { naziv: "kakao", kolicina: 5, jedinica: "gr" },
        ],
        priprema: "U šerpu sipati mleko i dodati griz.\nKuvati na laganoj vatri uz mešanje dok se ne zgusne.\nDodati kakao i med, pa sve dobro sjediniti.\nNa kraju dodati iseckanu bananu i sve dobro promešati.",
        savet: "Obavezno mutiti griz dok se kuva, kako ne bi došlo do grudvica.",
        kalorije: 493,
        porcije: 1,
        objectPosition: "30% 10%"
    },
    {
        id: 5,
        slika: tostJaja,
        naslov: "-TOST SA JAJIMA I PARADAJZOM-",
        opis: "Tost sa jajima i paradajzom je jednostavan, ali ukusan obrok koji je savršen za večeru. Hleb se tosti na puteru, dok se jaja prže do savršenog stepena, sa bogatim kajmakom koji dodaje kremastu teksturu. Paradajz unosi svežinu, a začini poput origana, bibera i čili pahuljica daju jelu dodatnu dimenziju ukusa. Ovaj obrok je brz i hranljiv, idealan za one koji žele ukusan obrok bez puno pripreme, a opet sa svim potrebnim nutrijentima.",
        vrsta: "večera",
        vreme: 10,
        sastojci: [
            { naziv: "hleb", kolicina: 2, jedinica: "kom" },
            { naziv: "jaje", kolicina: 2, jedinica: "kom" },
            { naziv: "kajmak", kolicina: 10, jedinica: "gr" },
            { naziv: "paradajz", kolicina: 1, jedinica: "kom" },
            { naziv: "so", kolicina: 2, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" },
            { naziv: "chilli flakes", kolicina: 3, jedinica: "gr" },
            { naziv: "puter", kolicina: 10, jedinica: "gr" },
            { naziv: "origano", kolicina: 1, jedinica: "gr" }
        ],
        priprema: "U tiganju zagrijati puter i staviti hleb da se tosti.\nU drugom tiganju pržiti jaja, pa dodati so, biber i origano.\nNa kraj iseći paradajz na kockice i dobro ga posoliti.\nNa tost staviti kajmak i paradajz, pa preko njih jaja.",
        savet: "Dodati sriracha sos na kraju, preko jaja, kako bi se dobio pikantniji ukus.",
        kalorije: 438,
        porcije: 1,
    },
    {
        id: 6,
        slika: krilca,
        naslov: "-HRSKAVA PILEĆA KRILCA-",
        opis: "Hrsava pileća krilca su savršen izbor za ljubitelje mesa koji žele uživati u hrskavom i ukusnom obroku. Krilca se pripremaju uz prah za pecivo, koji im daje dodatnu hrskavost, dok so i biber obogaćuju njihov prirodan ukus. Jednostavno za pripremu i savršeno za ručak, ovo jelo pruža pravu mešavinu ukusa i tekstura, idealno za ljubitelje pilećeg mesa.",
        vrsta: "ručak",
        vreme: 60,
        sastojci: [
            { naziv: "krilca", kolicina: 8, jedinica: "kom" },
            { naziv: "prašak za pecivo", kolicina: 4, jedinica: "gr" },
            { naziv: "so", kolicina: 4, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" }
        ],
        priprema: "U velikoj činiji pomešati krilca, prašak za pecivo, so i biber.\nSve dobro promešati da se krilca ravnomerno oblože smesom.\nOstaviti krilca da odstoje preko noći u frižideru.\nRernu zagrejati na 120 stepeni i staviti krilca da se peku 30 minuta.\nNakon toga, povećati temperaturu na 240 stepeni i peći još 30 minuta, sa okretanjem krilaca nakon 15 minuta, dok ne postanu zlatno smeđa i hrskava.",
        savet: "Za dodatnu hrskavost, možeš krilca peći na rešetki umesto na plehu.",
        kalorije: 706,
        porcije: 1,
    },
    {
        id: 7,
        slika: panko,
        naslov:"-POHOVANO BELO MESO-",
        opis: "Pohovano belo meso je klasik koji nikada ne izlazi iz mode. Piletina je uvaljana u brašno, jaje i panko prezle, a potom pržena do savršene hrskavosti. So, biber, origano i chilli flakes dodaju savršenu začinsku notu, dok puter doprinosi bogatstvu okusa. Ovo jelo je ukusan i zasitan ručak, koji će zadovoljiti i najizbirljivije gurmane.",
        vrsta: "ručak",
        vreme: 40,
        sastojci: [
            { naziv: "belo meso", kolicina: 200, jedinica: "gr" },
            { naziv: "panko prezle", kolicina: 50, jedinica: "gr" },
            { naziv: "brašno", kolicina: 30, jedinica: "gr" },
            { naziv: "jaje", kolicina: 1, jedinica: "kom" },
            { naziv: "so", kolicina: 2, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" },
            { naziv: "chilli flakes", kolicina: 3, jedinica: "gr" },
            { naziv: "puter", kolicina: 10, jedinica: "gr" },
            { naziv: "origano", kolicina: 1, jedinica: "gr" }
        ],
        priprema: "Belo meso iseći na tanke šnicle.\nZačiniti svaku šniclu sa soli, biberom, origanom i chilli flakes-om.\nSvaku šniclu prvo uvaljati u brašno, pa u umućeno jaje, a zatim u panko prezle.\nU tiganju zagrejati puter i pržiti šnicle sa obe strane dok ne postanu zlatno smeđe i hrskave.\nPoslužiti toplo uz prilog po izboru.",
        savet: "Umesto da začiniš meso, možeš dodati začine u brašno ili panko prezle, kako bi se dobio jači ukus.",
        kalorije: 659,
        porcije: 1,
    },
    {
        id: 8,
        slika: burito,
        naslov: "-BURITO SA BELIM MESOM-",
        opis: "Ovaj ukusan burito sa belim mesom je savršen obrok za večeru, sa laganim i osvežavajućim sastojcima poput piletine, humusa, paradajza, krastavca i začina. Tortilja u koju se sve upakuje dodaje savršen balans, a začini poput origana i chilli flakes-a daju mu dodatnu dozu ukusa. Brzo se sprema i može da bude savršen obrok za one koji žele nešto ukusno, ali i hranljivo. Svi sastojci zajedno čine ovaj burito izuzetno bogatim ukusima, dok istovremeno pruža dobar izvor proteina i zdravih masti.",
        vrsta: "večera",
        vreme: 30,
        sastojci: [
            { naziv: "belo meso", kolicina: 150, jedinica: "gr" },
            { naziv: "humus", kolicina: 20, jedinica: "gr" },
            { naziv: "tortilja", kolicina: 150, jedinica: "ml" },
            { naziv: "paradajz", kolicina: 0.5, jedinica: "kom" },
            { naziv: "krastavac", kolicina: 0.25, jedinica: "kom" },
            { naziv: "so", kolicina: 2, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" },
            { naziv: "chilli flakes", kolicina: 3, jedinica: "gr" },
            { naziv: "beli luk", kolicina: 3, jedinica: "čena" },
            { naziv: "puter", kolicina: 10, jedinica: "gr" },
            { naziv: "origano", kolicina: 2, jedinica: "gr" }
        ],
        priprema: "Belo meso iseckati na kockice i začiniti sa solju, biberom, origanom i chilli flakes-om.\nNa tiganju zagrejati puter i, pre dodavanja belog mesa, pržiti iseckani beli luk minut-dva.\nDodati belo meso i pržiti dok ne dobije zlatnu boju.\nNa tortilju staviti humus, paradajz, krastavac i prženo belo meso.\nSve dobro zamotati i poslužiti toplo.\nNa tortilju namazati malo humusa, pa dodati iseckano povrće i zamotati.",
        savet: "Umotani burito možeš dodatno zapeći u tiganju ili tosteru za tople sendviče, kako bi dobio hrskavu koricu.",
        kalorije: 516,
        porcije: 1,
    },
    {
        id: 9,
        slika: burger,
        naslov: "-BURGER-",
        opis: "Ovaj sočan i ukusan burger savršen je za brzu večeru, sa sočnim junećim mesom, svežim povrćem i začinima koji podižu sve ukuse. Piletina je jednostavno začinjena sa soli, biberom i origano, dok crni luk, beli luk i paradajz dodaju svežinu. Kiseli krastavčići i tucana paprika daju mu dodatnu aromu i začinjenost. Somun, u kojem se sve servira, doprinosi bogatom teksturalnom kontrastu, čineći ovaj burger savršenim obrokom za ljubitelje brze hrane.",
        vrsta: "večera",
        vreme: 15,
        sastojci: [
            { naziv: "juneće mleveno meso", kolicina: 200, jedinica: "gr" },
            { naziv: "somun", kolicina: 1, jedinica: "kom" },
            { naziv: "crni luk", kolicina: 1, jedinica: "kom" },
            { naziv: "beli luk", kolicina: 2, jedinica: "čena" },
            { naziv: "paradajz", kolicina: 0.5, jedinica: "kom" },
            { naziv: "kiseli krastavčići", kolicina: 2, jedinica: "kom" },
            { naziv: "so", kolicina: 2, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" },
            { naziv: "origano", kolicina: 2, jedinica: "gr" },
            { naziv: "tucana paprika", kolicina: 1, jedinica: "kašičica" }
        ],
        priprema: "Juneće meso začiniti sa solju, biberom, origanom i tucanom paprikom.\nOblikovati pljeskavicu i staviti je na roštilj ili u tiganj da se peče.\nU međuvremenu, na tiganju propržiti sitno seckani crni i beli luk.\nIseckati paradajz i kiseli krastavac na kolutove, propržiti somun u istom tiganju u kojem se meso peče.\nNa kraju, sve sastojke staviti u somun i poslužiti toplo.",
        savet: "Za dodatnu sočnost, može se dodati bilo koji sos po želji u somun pre nego što se stavi meso.",
        kalorije: 870,
        porcije: 1,
    },
    {
        id: 10,
        slika: pica,
        naslov:"-PICA-",
        opis: "Pica je omiljeni obrok mnogih, a u ovom receptu kombinuju se sočni kulen, pečurke, kiseli krastavčići i bogat kačkavalj, sve na hrskavom domaćem testu. Uz dodatak origana, bosiljka i začina, ova pizza donosi savršen balans ukusa. Savršena je za sve ljubitelje italijanske hrane, a može biti idealan obrok za večeru sa prijateljima ili porodicom. Sa bogatstvom sastojaka, lako možete da je podelite u više porcija i uživate u svakom zalogaju.",
        vrsta: "ručak",
        vreme: 50,
        sastojci: [
            { naziv: "brašno", kolicina: 350, jedinica: "gr" },
            { naziv: "so", kolicina: 6, jedinica: "gr" },
            { naziv: "šećer", kolicina: 8, jedinica: "gr" },
            { naziv: "voda", kolicina: 220, jedinica: "ml" },
            { naziv: "kvasac", kolicina: 10, jedinica: "gr" },
            { naziv: "kulen", kolicina: 100, jedinica: "gr" },
            { naziv: "kečap", kolicina: 50, jedinica: "ml" },
            { naziv: "kačkavalj", kolicina: 350, jedinica: "gr" },
            { naziv: "pečurke", kolicina: 5, jedinica: "kom" },
            { naziv: "kiseli krastavčići", kolicina: 6, jedinica: "kom" },
            { naziv: "origano", kolicina: 5, jedinica: "gr" },
            { naziv: "bosiljak", kolicina: 3, jedinica: "gr" },
            { naziv: "beli luk", kolicina: 5, jedinica: "čena" },
            { naziv: "chilli flakes", kolicina: 5, jedinica: "gr" }
        ],
        priprema: "U činiji pomešati brašno, so i šećer.\nU čašu dodati toplu vodu i kvasac i pustiti da odstoji 10 minuta.\nDodati vodu sa kvascem u činiju sa brašnom i sve dobro promešati dok se ne dobije glatko testo.\nOstaviti da odstoji preko noći.\nNakon toga, razvući testo na debljinu od 1 cm i staviti u pleh.\nSipati kečap u činiju i u njega ubaciti sitno iseckani beli luk, origano, bosiljak, so, biber i chilli flakes.\nPremazati testo dobijenim sosom, pa dodati kulen, pečurke i kiseli krastavčić.\nPeći u prethodno zagrejanoj rerni na 275 stepeni oko 8-9 minuta.\nNa kraju, izvaditi picu i posuti je rendanim kačkavaljem.\nVratiti u rernu dok se sir ne otopi i dobije zlatnu boju.",
        savet: "Umesto pleha, može se koristiti kamen za pečenje pice, kako bi se dobila hrskavija korica.",
        kalorije: 3240,
        porcije: 4,
    },
    {
        id: 11,
        slika: losos,
        naslov: "-LOSOS I POMFRIT-",
        opis: "Ovaj obrok spaja sočan losos sa hrskavim domaćim pomfritom, uz dodatak limuna za osvežavajući šmek. Prženi krompir u suncokretovom i maslinovom ulju daje savršenu teksturu i ukus, dok soja sos i kečap čine dodatnu dimenziju okusa. Idealno je jelo za uživanje u zdravoj i ukusnoj večeri, a kombinacija lososa i pomfrita čini obrok koji je i ukusan i zasitan.",
        vrsta: "ručak",
        vreme: 30,
        sastojci: [
            { naziv: "losos", kolicina: 300, jedinica: "gr" },
            { naziv: "krompir", kolicina: 200, jedinica: "gr" },
            { naziv: "kečap", kolicina: 50, jedinica: "ml" },
            { naziv: "suncokretovo ulje", kolicina: 200, jedinica: "ml" },
            { naziv: "maslinovo ulje", kolicina: 10, jedinica: "ml" },
            { naziv: "limun", kolicina: 0.25, jedinica: "kom" },
            { naziv: "soja", kolicina: 20, jedinica: "ml" },
            { naziv: "so", kolicina: 2, jedinica: "gr" },
            { naziv: "biber", kolicina: 2, jedinica: "gr" },
            { naziv: "tucana paprika", kolicina: 2, jedinica: "2gr" }
        ],
        priprema: "Krompir oljuštiti i iseći na štapiće.\nU tiganju zagrijati suncokretovo ulje i pržiti krompir dok ne postane zlatno smeđi i hrskav.\nLosos začiniti sa solju, biberom, tucanom paprikom i limunovim sokom.\nNa drugom tiganju zagrejati maslinovo ulje i pržiti losos sa svih strana dok ne dobije zlatnu boju i na kraju dodati soja sos.\nNa kraju, sve servirati zajedno uz kečap.",
        savet: "Umesto kečapa, možeš koristiti tartar sos ili neki drugi umak po izboru.",
        kalorije: 1040,
        porcije: 1,
    },
    {
        id: 12,
        slika: sendvic,
        naslov: "-TOPLI SENDVIČI-",
        opis: "Topli sendviči su savršen izbor za brz, ali ukusan doručak. Hrskavi hleb, rastopljeni kačkavalj, aromatični kečap i začini poput origana čine ovaj sendvič neodoljivim, dok kulen dodaje dodatni sloj bogatog ukusa. Uz malo putera, ovaj jednostavan, a ukusan obrok može biti odličan način da započneš dan sa energijom.",
        vrsta: "doručak",
        vreme: 10,
        sastojci: [
            { naziv: "hleb", kolicina: 2, jedinica: "kom" },
            { naziv: "kačkavalj", kolicina: 30, jedinica: "gr" },
            { naziv: "kečap", kolicina: 10, jedinica: "ml" },
            { naziv: "origano", kolicina: 1, jedinica: "gr" },
            { naziv: "kiseli krastavčići", kolicina: 1, jedinica: "kom" },
            { naziv: "kulen", kolicina: 15, jedinica: "gr" },
            { naziv: "puter", kolicina: 5, jedinica: "gr" },
        ],
        priprema: "Na svaki komad hleba staviti kečap, kulen, kiseli krastavčić i kačkavalj.\nPreklopiti svaki komad hleba sa još jednim parčetom hleba i premazati spoljne strane puterom.\nPoklopiti toster za tople sendviče i peći dok se sir ne otopi i hleb ne postane zlatno smeđi.\nNa kraju, posuti origano preko sendviča.",
        savet: "Pored kečapa, može se koristiti i majonez i time napraviti ukusniji sos.\n(To će uticati na kalorije)",
        kalorije: 406,
        porcije: 1,
    },
    {
        id: 13,
        slika: chia,
        naslov:"-CHIA PUDING-",
        opis: "Chia puding je ukusan i zdrav dezert koji je brz za pripremu. Chia semenke upijaju mleko i stvaraju želatinastu teksturu, dok med dodaje prirodnu slatkoću. Služeni sa svežim jagodama i komadićima crne čokolade, ovaj puding postaje pravo uživanje u ukusu i hranljivim sastojcima. Idealno je rešenje za desert koji je i ukusan i hranljiv.",
        vrsta: "dezert",
        vreme: 5,
        sastojci: [
            { naziv: "chia semenke", kolicina: 30, jedinica: "gr" },
            { naziv: "mleko", kolicina: 150, jedinica: "ml" },
            { naziv: "med", kolicina: 15, jedinica: "gr" },
            { naziv: "jagode", kolicina: 7, jedinica: "kom" },
            { naziv: " crna čokolada", kolicina: 20, jedinica: "gr" }
        ],
        priprema: "U činiji pomešati chia semenke, mleko i med.\nSve dobro promešati i ostaviti da odstoji 30 minuta ili preko noći u frižideru.\nPre služenja, dodati iseckane jagode i komadiće crne čokolade.",
        savet: "Dodati muskatni oraščić ili cimet u smesu sa chia semenkama za dodatni ukus.",
        kalorije: 425,
        porcije: 1,
    },
    {
        id: 14,
        slika: pesto,
        naslov: "-PESTO PASTA-",
        opis: "Pesto pasta je jednostavno jelo koje spaja ukuse svežeg bosiljka, začinskog origana i bogatog pesto sosa. Čeri paradajz dodaje svežinu, dok pavlaka za kuvanje daje kremastu teksturu koja čini svaki zalogaj posebnim. Savršeno je za brzi ručak koji je ukusan, zasitan i bogat vitaminima. Idealno je za ljubitelje italijanske kuhinje koji žele da uživaju u jednostavnom, ali punom okusu.",
        vrsta: "ručak",
        vreme: 20,
        sastojci: [
            { naziv: "pasta", kolicina: 170, jedinica: "gr" },
            { naziv: "pesto", kolicina: 95, jedinica: "gr" },
            { naziv: "čeri paradajz", kolicina: 300, jedinica: "gr" },
            { naziv: "kačkavalj", kolicina: 50, jedinica: "gr" },
            { naziv: "pavlaka za kuvanje", kolicina: 125, jedinica: "ml" },
            { naziv: "so", kolicina: 3, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" },
            { naziv: "bosiljak", kolicina: 5, jedinica: "gr" },
            { naziv: "origano", kolicina: 5, jedinica: "gr" }
        ],
        priprema: "U šerpi zagrejati vodu i dodati so. Kada voda proključa, dodati pastu i kuvati prema uputstvu na pakovanju.\nU međuvremenu, u tiganju zagrijati pesto sos i dodati čeri paradajz sa začinima.\nKada je pasta gotova, procediti je i dodati u tiganj sa pestom i paradajzom.\nSve dobro promešati i na kraju dodati pavlaku za kuvanje i sir.\nKuvati još nekoliko minuta dok se sve ne sjedini.\nSlužiti toplo, po želji posuto svežim bosiljkom ili parmezanom.",
        savet: "Na kraju se može dodati parmezan za dodatni ukus.",
        kalorije: 986,
        porcije: 2,
    },
    {
        id: 15,
        slika:pastaPecurke,
        naslov: "-PASTA SE BELIM MESOM I PEČURKAMA-",
        opis: "Pasta sa belim mesom i pečurkama je ukusno i kremasto jelo koje kombinuje nežno belo meso i bogate pečurke, u savršenom spoju sa kremastom pavlakom za kuvanje. Začini poput origana, bosiljka, i tucane paprike dodaju dubinu okusa, dok pasta upija sve te ukuse. Jelo je brzo, zasitno i idealno za svaki obrok kada želite nešto brzo i ukusanog.",
        vrsta: "ručak",
        vreme: 40,
        sastojci: [
            { naziv: "belo meso", kolicina: 150, jedinica: "gr" },
            { naziv: "pečurke", kolicina: 200, jedinica: "gr" },
            { naziv: "pasta", kolicina: 170, jedinica: "gr" },
            { naziv: "pavlaka za kuvanje", kolicina: 200, jedinica: "ml" },
            { naziv: "so", kolicina: 5, jedinica: "gr" },
            { naziv: "biber", kolicina: 2, jedinica: "gr" },
            { naziv: "tucana paprika", kolicina: 5, jedinica: "gr" },
            { naziv: "chilli flakes", kolicina: 5, jedinica: "gr" },
            { naziv: "bosiljak", kolicina: 5, jedinica: "gr" },
            { naziv: "origano", kolicina: 5, jedinica: "gr" }
        ],
        priprema: "Skuvaj pastu u posoljenoj vodi, procedi i sačuvaj malo vode od kuvanja.\nIseci belo meso i proprži ga na ulju dok ne porumeni.\nDodaj seckane pečurke i prži dok ne omekšaju.\nUbaci začine (so, biber, tucana paprika, chilli flakes, bosiljak, origano) i kratko proprži.\nSipaj pavlaku za kuvanje i krčkaj nekoliko minuta dok se sos ne zgusne.\nUbaci pastu, sve promešaj i po potrebi dodaj malo vode od kuvanja da razrediš sos.",
        savet: "Služi toplo, po želji uz parmezan ili sveži bosiljak.",
        kalorije: 1153,
        porcije: 2,
    },
    {
        id: 16,
        slika: cheesecake,
        naslov:"-CHEESECAKE-",
        opis: "Cheesecake sa malinama je kremasti dezert koji spaja bogatstvo kisele pavlake i slatkoću malina. U osnovi je hrskava kora od mlevene plazme i putera, dok je gornji sloj bogat kremom od Ella sira, slatke pavlake i šećera, sa dodatkom želatina koji daje stabilnost. Na vrhu se nalazi osvežavajući sloj malina, sa malo šećera i vanilin šećera za dodatnu aromu. Savršen spoj bogatog, ali nežnog ukusa i osvežavajuće voćne note malina.",
        vrsta: "dezert",
        vreme: 80,
        sastojci: [
            { naziv: "mlevena plazma", kolicina: 300, jedinica: "gr" },
            { naziv: "puter", kolicina: 125, jedinica: "gr" },
            { naziv: "mleko", kolicina: 70, jedinica: "ml" },
            { naziv: "Ella sir", kolicina: 450, jedinica: "gr" },
            { naziv: "slatka pavlaka", kolicina: 500, jedinica: "ml" },
            { naziv: "želatin", kolicina: 3, jedinica: "kesice" },
            { naziv: "šećer u prahu", kolicina: 200, jedinica: "gr" },
            { naziv: "vanilin šećer", kolicina: 1, jedinica: "kesica" },
            { naziv: "kremfix", kolicina: 1, jedinica: "kesica" },
            { naziv: "malina", kolicina: 450, jedinica: "gr" },
            { naziv: "šećer", kolicina: 50, jedinica: "gr" }
        ],
        priprema: "U činiji pomešati mlevenu plazmu i otopljeni puter.\nDodati mleko i sve dobro sjediniti.\nSmestiti u pleh i ostaviti da se stegne.\nU drugoj činiji umutiti slatku pavlaku, dodati Ella sir, šećer u prahu, vanilu i kremfix.\nU posebnoj činiji pripremiti želatin prema uputstvu na pakovanju i dodati u smesu sa sirom.\nSve dobro sjediniti i preliti preko kore od plazme.\nOstaviti da se stegne u frižideru.\nMaline skuvati sa šećerom i vanilijom i dodati želatin, pa preliti preko čizkejk-a.",
        savet: "Svako parče čizkejka se može posuti mrvicama od keksa ili rendanom čokoladom i ukrasiti malinom ili jagodom.",
        kalorije: 7170,
        porcije: 8,
    },
    {
        id: 17,
        slika: mus,
        naslov: "-ČOKOLADNI MUS-",
        opis: "Čokoladni mus je kremasti, bogati dezert savršen za ljubitelje čokolade. Kremasta tekstura se postiže kombinovanjem otopljene crne čokolade sa umućenim jajima i slatkom pavlakom. Puter i šećer u prahu dodaju glatkoću i dodatnu slatkoću. Ovaj mus je idealan za uživanje u malim porcijama, a njegov intenzivan čokoladni ukus je prava poslastica za sve sladokusce.",
        vrsta: "dezert",
        vreme: 15,
        sastojci: [
            { naziv: "crna čokolada", kolicina: 125, jedinica: "gr" },
            { naziv: "jaja", kolicina: 3, jedinica: "kom" },
            { naziv: "slatka pavlaka", kolicina: 120, jedinica: "ml" },
            { naziv: "puter", kolicina: 10, jedinica: "gr" },
            { naziv: "šećer u prahu", kolicina: 25, jedinica: "gr" }
        ],
        priprema: "Otopiti čokoladu na pari ili u mikrotalasnoj.\nU drugoj činiji umutiti jaja i dodati otopljenu čokoladu.\nU trećoj činiji umutiti slatku pavlaku sa šećerom u prahu i dodati u smesu sa čokoladom.\nSve dobro sjediniti i staviti u čaše ili posude za serviranje.\nOstaviti da se stegne u frižideru.",
        savet: "Mogu se dodati komadići čokolade ili voće kao dekoracija.",
        kalorije: 1420,
        porcije: 2,
    },
    {
        id: 18,
        slika: rolnice,
        naslov: "-CIMET ROLNICE-",
        opis: "Cimet rolnice su ukusan i mirisan dezert koji je savršen za ljubitelje slatkiša i začina. Kvasac, brašno i šećer se kombinuju sa kremastim puterom, cimetom i vanilin ekstraktom da bi se stvorila bogata tekstura i sladak, začinski ukus. Ovaj recept je odličan za svakog ko želi da uživa u svežim i mekanim rolnicama sa bogatim punjenjem, idealnim za doručak ili užinu.",
        vrsta: "dezert",
        vreme: 60,
        sastojci: [
            { naziv: "kvasac", kolicina: 1, jedinica: "kesica" },
            { naziv: "mleko", kolicina: 350, jedinica: "ml" },
            { naziv: "šećer", kolicina: 100, jedinica: "gr" },
            { naziv: "puter", kolicina: 265, jedinica: "gr" },
            { naziv: "so", kolicina: 3, jedinica: "gr" },
            { naziv: "jaje", kolicina: 2, jedinica: "kom" },
            { naziv: "brašno", kolicina: 500, jedinica: "gr" },
            { naziv: "smeđi šećer", kolicina: 200, jedinica: "gr" },
            { naziv: "cimet", kolicina: 20, jedinica: "gr" },
            { naziv: "šećer u prahu", kolicina: 150, jedinica: "gr" },
            { naziv: "kremsir", kolicina: 60, jedinica: "gr" },
            { naziv: "vanilin ekstrakt", kolicina: 3, jedinica: "ml" }
        ],
        priprema: "U velikoj posudi pomešati mleko, šećer i kvasac i dobro sjediniti. Ostaviti da odstoji 10 minuta.\nNakon toga, dodati otopljeni puter, jaja, brašno, smeđi šećer i cimet. Sve dobro promešati, urolati i ostaviti da naraste 30 minuta.\nDobijenu rolnu iseći na 12 jednakih komada i staviti u pleh.\nZatim peći u prethodno zagrejanoj rerni na 180°C oko 25 minuta.\n Nakon toga, napraviti fil od krem sira, šećera u prahu i vanilin ekstrakta i premazati preko pečenih rolnica.\nPoslužiti toplo ili hladno.",
        savet: "Rolnice se mogu poslužiti sa dodatkom voća ili čokolade za još bogatiji ukus.",
        kalorije: 5953,
        porcije: 12,
    },
    {
        id: 19,
        slika: split,
        naslov:"-BANANA SPLIT-",
        opis: "Banana Split je ukusan i osvežavajući dezert koji kombinuje sladoled, voće i šlag u savršenoj harmoniji ukusa. U ovoj verziji, osnovu čini sočna banana, na kojoj se nalazi kugla sladoleda od banane, čokolade i vanile, dok je sve preliveno čokoladnim prelivom, šlagom i dekorisano sa nekoliko višanja. Ovaj dezert je brz i jednostavan za pripremu, a istovremeno pruža bogatstvo ukusa koji se savršeno kombinuju u svakom zalogaju. Idealno je kao osvežavajući završetak obroka ili za uživanje u toplim letnjim danima.",
        vrsta: "dezert",
        vreme: 5,
        sastojci: [
            { naziv: "banana", kolicina: 1, jedinica: "kugla" },
            { naziv: "sladoled banana", kolicina: 1, jedinica: "kugla" },
            { naziv: "sladoled cokolada", kolicina: 1, jedinica: "kugla" },
            { naziv: "sladoled vanila", kolicina: 1, jedinica: "kom" },
            { naziv: "preliv cokolada", kolicina: 10, jedinica: "gr" },
            { naziv: "šlag", kolicina: 1, jedinica: "kugla" },
            { naziv: "višnja", kolicina: 3, jedinica: "kom" }
        ],
        priprema: "Oljuštiti bananu i prepoloviti je po dužini.\nNa tanjir staviti polovinu banane, pa dodati kuglu sladoleda od banane, čokolade i vanile.\nPreliti čokoladnim prelivom, dodati šlag i dekorisati sa višnjama.",
        savet: "Može se dodati i mleveni keks ili čokoladne mrvice za dodatnu teksturu.",
        kalorije: 592,
        porcije: 1,
    },
    {
        id: 20,
        slika: cufte,
        naslov: "-JUNEĆE ĆUFTE SA PIREOM-",
        opis: "Juneće ćufte sa pireom je klasičan i ukusan obrok koji spaja bogatstvo mesa i kremastu teksturu pire krompira. Juneće meso se meša sa začinima i prezlama, oblikuje u ćufte, a zatim se peče dok ne postane sočno i savršeno začinjeno. Pire krompir je napravljen sa malo mleka i prstohvatom muskatnog oraha, što mu daje dodatnu mekoću i bogatstvo ukusa. Na kraju, sve se preliva paradajz sosom, što dodaje sočnost i blagost ovom jelu. Ovo je savršen obrok za ljubitelje tradicionalne kuhinje.",
        vrsta: "ručak",
        vreme: 50,
        sastojci: [
            { naziv: "juneće mleveno meso", kolicina: 400, jedinica: "gr" },
            { naziv: "prezle", kolicina: 30, jedinica: "gr" },
            { naziv: "krompir", kolicina: 400, jedinica: "gr" },
            { naziv: "mleko", kolicina: 20, jedinica: "ml" },
            { naziv: "muskatni orah", kolicina: 1, jedinica: "prstohvat" },
            { naziv: "paradajz sos", kolicina: 200, jedinica: "ml" },
            { naziv: "so", kolicina: 5, jedinica: "gr" },
            { naziv: "biber", kolicina: 2, jedinica: "gr" },
            { naziv: "tucana paprika", kolicina: 2, jedinica: "gr" },
            { naziv: "origano", kolicina: 5, jedinica: "gr" }
        ],
        priprema: "Oljuštiti krompir i skuvati ga u slanoj vodi.\nU međuvremenu, pomešati mleveno meso, prezle, so, biber, tucanu papriku i origano.\nOblikovati ćufte i peći ih u tiganju sa malo ulja dok ne dobiju zlatnu boju.\nKrompir procediti, dodati mleko, muskatni orah i izgnječiti u pire.\nNa kraju, servirati ćufte preko pirea i preliti paradajz sosom.",
        savet: "Uz ćufte se može poslužiti i sveža salata ili neki lagani prilog.",
        kalorije: 1072,
        porcije: 2,
    },
    {
        id: 21,
        slika: steak,
        naslov: "-STEAK-",
        opis: "Steak je sočan komad mesa, obično biftek, koji je brzo pečen u tiganju sa minimalnim začinima poput soli, bibera i maslinovog ulja. Dodavanje belog luka i ruzmarina doprinosi intenzivnijem ukusu, dok puter na kraju dodaje bogatstvo i sočnost jelu. Ovo jelo je jednostavno, ali ukusno, savršeno za ljubitelje mesa.",
        vrsta: "ručak",
        vreme: 15,
        sastojci: [
            { naziv: "biftek", kolicina: 300, jedinica: "gr" },
            { naziv: "beli luk", kolicina: 5, jedinica: "čena" },
            { naziv: "ruzmarin", kolicina: 1, jedinica: "kom" },
            { naziv: "puter", kolicina: 25, jedinica: "gr" },
            { naziv: "maslinovo ulje", kolicina: 15, jedinica: "ml" },
            { naziv: "so", kolicina: 5, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" }
        ],
        priprema: "U tiganju zagrejati maslinovo ulje i dodati prethodno posoljen biftek.\nPržiti sa obe strane dok ne dobije zlatnu boju.\nDodati beli luk, ruzmarin i puter, pa pržiti još nekoliko minuta.\nNa kraju, posoliti i pobiberiti po ukusu.",
        savet: "Ostaviti meso da odstoji nekoliko minuta pre sečenja kako bi se sokovi ravnomerno rasporedili.",
        kalorije: 870,
        porcije: 1,
    },
    {
        id: 22,
        slika: makaroneSir,
        naslov:"-MAKARONE SA SIROM-",
        opis: "Ovaj recept za makarone sa sirom je brz i ukusan obrok, idealan za večeru. Pasta se kombinuje sa kremastim feta sirom i pavlakom, uz svež paradajz, beli luk i začine kao što su bosiljak i origano, što daje odličnu ravnotežu ukusa. Jednostavno, a vrlo zasitno!",
        vrsta: "večera",
        vreme: 20,
        sastojci: [
            { naziv: "pasta", kolicina: 170, jedinica: "gr" },
            { naziv: "feta", kolicina: 250, jedinica: "gr" },
            { naziv: "pavlaka", kolicina: 30, jedinica: "gr" },
            { naziv: "paradajz", kolicina: 2, jedinica: "kom" },
            { naziv: "maslinovo ulje", kolicina: 10, jedinica: "ml" },
            { naziv: "beli luk", kolicina: 5, jedinica: "čena" },
            { naziv: "so", kolicina: 3, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" },
            { naziv: "beli luk u prahu", kolicina: 5, jedinica: "gr" },
            { naziv: "bosiljak", kolicina: 5, jedinica: "gr" },
            { naziv: "origano", kolicina: 5, jedinica: "gr" }
        ],
        priprema: "U posoljenoj vodi skuvati pastu prema uputstvu na pakovanju.\nU međuvremenu, u tiganju zagrijati maslinovo ulje i propržiti beli luk.\nDodati iseckani paradajz i začine.\nU posebnu posudu staviti pavlaku i feta sir i dobro sjediniti.\nKuvanu pastu procediti i dodati u posudu sa fetom i pavlakom.\n U istu posudu dodati i sos od belog luka, paradajza i začina.\nSve dobro promešati i poslužiti.",
        savet: "Može se dodati i rendani parmezan i ukrasiti svežim bosiljkom.",
        kalorije: 1495,
        porcije: 2,
    },
    {
        id: 23,
        slika: tostAvokado,
        naslov: "-TOST SA JAJIMA I AVOKADOM-",
        opis: "Tost sa jajima i avokadom je jednostavan, ukusan i hranljiv doručak koji kombinuje kremasti avokado, bogata jaja i hrskav hleb, sa dodatkom začina koji obogaćuju ukus. Idealno je za početak dana, jer pruža dobar izvor zdravih masti, proteina i vlakana.",
        vrsta: "doručak",
        vreme: 15,
        sastojci: [
            { naziv: "hleb", kolicina: 2, jedinica: "kom" },
            { naziv: "avokado", kolicina: 1, jedinica: "kom" },
            { naziv: "jaje", kolicina: 2, jedinica: "kom" },
            { naziv: "maslinovo ulje", kolicina: 10, jedinica: "ml" },
            { naziv: "so", kolicina: 2, jedinica: "gr" },
            { naziv: "biber", kolicina: 1, jedinica: "gr" },
            { naziv: "tucana paprika", kolicina: 3, jedinica: "gr" },
            { naziv: "origano", kolicina: 2, jedinica: "gr" }
        ],
        priprema: "Na tiganju zagrejati maslinovo ulje i ispržiti jaja na oko.\nHleb tostirati u tosteru ili na tiganju.\nAvokado izgnječiti viljuškom i dodati so, biber, tucanu papriku i origano.\nNa tost staviti avokado, pa preko njega pržena jaja.\nPoslužiti toplo.",
        savet: "Može se dodati i paradajz ili sveža salata za dodatnu svežinu.",
        kalorije: 646,
        porcije: 1,
    },
    {
        id: 24,
        slika: palacinke,
        naslov: "-PALAČINKE-",
        opis: "Palačinke su omiljeni dezert koji je jednostavan za pripremu i može se prilagoditi različitim dodacima poput džema, čokolade, voća ili šlaga. Sastojci kao što su brašno, mleko, jaja i voda kombinuju se u glatku smesu koja se prži na tavi s malo ulja, dok vanilin ekstrakt dodaje prijatan miris i ukus. Palačinke su tanje i mekše, idealne za uživanje u kombinaciji sa raznim dodacima po želji. Ovaj brzi i ukusan desert može biti savršen za doručak ili užinu.",
        vrsta: "dezert",
        vreme: 25,
        sastojci: [
            { naziv: "brašno", kolicina: 200, jedinica: "gr" },
            { naziv: "voda", kolicina: 200, jedinica: "ml" },
            { naziv: "mleko", kolicina: 200, jedinica: "ml" },
            { naziv: "jaje", kolicina: 2, jedinica: "kom" },
            { naziv: "suncokretovo ulje", kolicina: 15, jedinica: "ml" },
            { naziv: "vanilin ekstrakt", kolicina: 3, jedinica: "ml" }
        ],
        priprema: "U posudi pomešati brašno, mleko, vodu, jaja, ulje i vanilu.\nSve dobro sjediniti da se dobije glatka smesa.\nNa tiganju zagrejati malo ulja i sipati smesu u tankom sloju.\nPržiti sa obe strane dok ne porumeni.\nPoslužiti toplo sa dodacima po želji.",
        savet: "Palačinke se mogu puniti sa džemom, čokoladom, voćem ili sladoledom.",
        kalorije: 1082,
        porcije: 4,
    },

]

export default pilule;